import { Roboto } from "next/font/google";
import "../(remaining)/globals.css";
import NextThemeProvider from "@/components/Theme/ThemeProvider";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "500", "700", "900"],
  style: ["normal", "italic"],
  display: "auto",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} font-light`}>
        <NextThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          {children}
        </NextThemeProvider>
      </body>
    </html>
  );
}
