const task = [
  {
    id: 1,
    title: "web development ",
    status: "backlog",
    description: "lorem ipsum....",
    priority: "low",
    category: "research",
    date: "April 23 ,2024",
  },
  {
    id: 11,
    title: "web development ",
    status: "backlog",
    description: "lorem ipsum....",
    priority: "low",
    category: "research",
    date: "April 23 ,2024",
  },
  {
    id: 12,
    title: "web development ",
    status: "backlog",
    description: "lorem ipsum....",
    priority: "low",
    category: "research",
    date: "April 23 ,2024",
  },
  {
    id: 31,
    title: "web development ",
    status: "backlog",
    description: "lorem ipsum....",
    priority: "low",
    category: "research",
    date: "April 23 ,2024",
  },
  {
    id: 2,
    title: "Content Writing  ",
    status: "On going",
    description: "lorem ipsum....",
    priority: "low",
    category: "Design",
    date: "April 24 ,2024",
  },
  {
    id: 4,
    title: "App Development  ",
    status: "Pending",
    description: "lorem ipsum....",
    priority: "high",
    category: "Planing",
    date: "April 24 ,2024",
  },
  { 
    id: 4,
    title: "App Development  ",
    status: "Pending",
    description: "lorem ipsum....",
    priority: "high",
    category: "Planing",
    date: "April 24 ,2024",
  },
];
