import { Inter } from "next/font/google";
import "./globals.css";
import NextThemeProvider from "@/components/Theme/ThemeProvider";
import NavComp from "@/components/Navbar/NavComp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NextThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <NavComp />
          {children}
        </NextThemeProvider>
      </body>
    </html>
  );
}
