import { Roboto } from "next/font/google";
import "./globals.css";
import NextThemeProvider from "@/components/Theme/ThemeProvider";
import SidebarComp from "@/components/Sidebar/Sidebar";
import NavComp from "@/components/Navbar/NavComp";
const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "500", "700", "900"],
  style: ["normal", "italic"],
  display: "auto",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} font-light`}>
        <NextThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <div className="flex items-start">
            {/* Side bar or Navigation */}
            <div className="flex-grow">
              {" "}
              <SidebarComp />
            </div>
            {/* Side bar or Navigation */}
            {/* main Children or Page  */}
            <main className="flex-grow">
              <div>
                <NavComp />
              </div>
              <div>
                {/* Main Content  */}
                {children}
                {/* Main Content  */}
              </div>
            </main>
            {/* main Children or Page  */}
          </div>
        </NextThemeProvider>
      </body>
    </html>
  );
}
